name: Run tests

on:
    push:
        branches: [master]

jobs:
    find-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check if tests exist
              run: |
                  if [ -f tests/test.sh ]; then
                      echo "" > napaka.txt
                  else
                      echo "Couldn't find tests" > napaka.txt
                  fi

            - name: Store errors in artifact
              uses: actions/upload-artifact@v3
              with:
                  name: errors
                  path: napaka.txt

    run-tests:
        runs-on: ${{ matrix.os }}
        needs: [find-tests]
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20.04]
        steps:
            - name: Download errors from artifact
              uses: actions/download-artifact@v2
              with:
                  name: errors

            - name: Check test errors
              run: |
                  [ "$(cat napaka.txt)" = "$(echo "")" ]

            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install dependencies
              run: sudo apt-get update -y && sudo apt-get install -y gcc-multilib

            - name: Run tests
              run: make test

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: [run-tests]
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v2
    #
    #         - name: Build and push image to DockerHub
    #           run: ./zapakiraj_27109.sh ${{ secrets.DOCKERHUB_TOKEN }}
    #
    #         - name: Run Docker image
    #           run: ./zazeni_27109.sh
